import {asset} from '@/lib/paths';
import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {FileText,FolderOpen,Check,Play,MoveUpRight,ArrowLeft,ArrowRight,Lightbulb} from 'lucide-react';
import Gallery from '@/components/gallery';
import ArticleNavigation from '@/components/article-navigation';
import ProjectPreview from '@/components/project-preview';
import {projects} from '@/data/projects';
import {stories} from '@/data/stories';

export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const p=projects.find(p=>p.slug===slug);return {title:p?.title,description:p?.summary}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}) {
  const{slug}=await params,project=projects.find(p=>p.slug===slug);if(!project)notFound();
  const index=projects.findIndex(p=>p.slug===slug),next=projects[(index+1)%projects.length],story=stories[slug];
  const words=[...story.intro,project.challenge,...project.decisions.map(d=>d.body),...project.contribution].join(' ').split(/\s+/).length;
  return <main id="main" className={'case-page case-'+slug}>
    <header className="case-hero shell"><div className="case-breadcrumb"><Link href="/#work"><ArrowLeft size={16}/>All projects</Link><span>{project.category}</span></div><div className={'case-hero-layout '+(!project.gallery.length?'without-preview':'')}><div className="case-hero-copy"><div className="case-title-row"><h1>{project.title}</h1><span className="case-status"><span className="status-dot"/>{project.status}</span></div><p className="case-deck">{project.summary}</p><div className="case-tool-list">{project.tools.map(t=><span key={t}>{t}</span>)}</div><p className="case-read-time">{Math.max(2,Math.ceil(words/200))} min read / {project.period.includes('2026')?'2026':project.period.includes('2025')?'2025':'2024'}</p></div>{project.gallery.length>0&&<ProjectPreview key={slug} items={project.gallery}/>}</div></header>
    <ArticleNavigation gallery={project.gallery.length>0}/>
    <section id="overview" className="shell article-section case-overview"><aside className="case-meta"><dl><div><dt>Context</dt><dd>{project.context}</dd></div><div><dt>Timeline</dt><dd>{project.period}</dd></div><div><dt>My role</dt><dd>{project.role}</dd></div></dl></aside><article className="project-article"><p className="section-context">The project, in brief</p><h2>{project.shortTitle}</h2>{story.intro.map(p=><p key={p}>{p}</p>)}<div className="article-takeaway"><Lightbulb size={22}/><div><strong>What came out of it</strong><p>{story.takeaway}</p></div></div></article></section>
    {project.gallery.length>0&&<section id="gallery" className="shell gallery-section article-section"><div className="section-heading"><div><p className="section-context">A closer look</p><h2>Explore the build.</h2></div><p>Switch views. Open an image. Inspect the detail.<br className="desktop-break"/> Original imagery from the project.</p></div><Gallery key={slug} items={project.gallery}/>{slug==='tof-slam'&&<div className="simulation"><div><span className="simulation-icon"><Play size={22}/></span><h3>See the mapping workflow.</h3><p>MATLAB software-in-the-loop visualization. This recording shows simulation rather than a physical test.</p></div><video controls preload="none" playsInline aria-label="MATLAB SLAM simulation"><source src={asset('/images/projects/slam-simulation.mp4')} type="video/mp4"/><p>Your browser cannot play this video. <a href={asset('/images/projects/slam-simulation.mp4')}>Download the simulation video.</a></p></video></div>}</section>}
    <section id="engineering" className="shell article-section case-content"><div className="case-text-section"><div><p className="section-context">Behind the decisions</p><h2>Inside the<br/>engineering.</h2></div><div className="engineering-detail"><p className="case-body-lead">{project.challenge}</p><div className="decision-list">{project.decisions.map((d,i)=><details key={d.title} open={i===0}><summary><h3>{d.title}</h3><span className="details-symbol"/></summary><p>{d.body}</p></details>)}</div></div></div><div className="case-text-section contribution"><div><h2>My contribution.</h2><p>Where I focused my work.</p></div><ul>{project.contribution.map(c=><li key={c}><Check size={18}/><span>{c}</span></li>)}</ul></div><div className="evidence-block"><FileText size={24}/><div><h3>What the evidence shows</h3><p>{project.evidence}</p></div></div></section>
    <section id="files" className="case-files article-section"><div className="shell case-text-section"><div><p className="section-context">Keep exploring</p><h2>The working files.</h2><p>Original documentation and source material.</p></div><div className="document-links">{project.files.map(f=><a key={f.href} href={asset(f.href)} target="_blank" rel="noopener noreferrer"><FileText size={20}/><span>{f.label}</span><span>{f.href.startsWith('https:')?'GitHub':f.href.endsWith('.csv')?'CSV':f.href.endsWith('.html')?'BOM':'PDF'}<MoveUpRight size={15}/></span></a>)}{slug!=='posture-research'&&<Link className="all-files" href={'/archive/?project='+slug}><FolderOpen size={21}/><span>Browse all project files</span><ArrowRight size={17}/></Link>}</div></div></section>
    <section className="next-project shell"><div><p>Up next</p><Link href={'/projects/'+next.slug+'/'}><h2>{next.title}</h2><span>Read the story<MoveUpRight size={22}/></span></Link></div>{next.image&&<Link className="next-project-image" href={'/projects/'+next.slug+'/'} aria-label={'Read '+next.title}><img src={asset(next.image)} alt="" width="600" height="400" loading="lazy"/></Link>}</section>
  </main>;
}
